on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Npm install and Tests
      run: |
        npm install
        npm run test:ci
        npm run test:cypress:ci

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Save
      run: |
        git config user.email "alvaro.alf2@gmail.com"
        git config user.name "Tserewara"
        git add -A && git commit -m "chore: deploy"
    
    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "fordevs-tserewara-react"
        heroku_email: "alvaro.alf2@gmail.com"

        